### ISSUE TITLE
在新版本的 Telegraph-Image 上失效

### ISSUE THREAD

**Issue by frinkleko** [secflag/picgo-plugin-telegraph-image#1]
本项目在[新版本](https://github.com/cf-pages/Telegraph-Image/commit/fad1cb8255c322525bcae076359a8ec49a5552b2)上失效。
于该仓库issue中发现[同质问题](https://github.com/cf-pages/Telegraph-Image/issues/13#issuecomment-1402106801)。
对于现有版本telegraph-image仓库，本插件皆失效。

picgo 版本2.3.1，2.4.0皆不成功。应当不是picgo的问题。
日志不报错，但是通知栏报405。
```2023-01-26 23:11:49 [PicGo INFO] Before transform
2023-01-26 23:11:49 [PicGo INFO] Transforming... Current transformer is [path] 
2023-01-26 23:11:49 [PicGo INFO] Before upload 
2023-01-26 23:11:49 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-01-26 23:11:49 [PicGo INFO] Uploading... Current uploader is [telegraph-image] 
2023-01-26 23:11:59 [PicGo SUCCESS] ````

**Comment by frinkleko** [comment]
可能是写法有些小问题，直接使用配置原插件不会出现问题。
![image](https://user-images.githubusercontent.com/32212221/215051701-361e5aae-0a5b-4cd4-848d-ca38e675f6c5.png)
之后我读代码后会尝试修改并pull requests。

**Comment by chen-can** [comment]
<img width="729" alt="image" src="https://github.com/secflag/picgo-plugin-telegraph-image/assets/35422769/68455a0b-eafe-476f-899f-3612650e8897">

设置代理:https://127.0.0.1:7890修复

**Comment by Xiao-Fangff** [comment]
> 可能是写法有些小问题，直接使用配置原插件不会出现问题。 ![image](https://user-images.githubusercontent.com/32212221/215051701-361e5aae-0a5b-4cd4-848d-ca38e675f6c5.png) 之后我读代码后会尝试修改并pull requests。

我参考您的参数进行配置，但是会出现 `返回解析失败` 的问题，请问如何解决？
![image](https://github.com/secflag/picgo-plugin-telegraph-image/assets/92212954/27ee93b4-24b8-41fa-8e56-f8ee2dcd0a67)
![image](https://github.com/secflag/picgo-plugin-telegraph-image/assets/92212954/c29122eb-cde4-4e2e-834e-789c88e85968)
